import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";

// componentes
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "ConsoLearn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link>
      <body className={`${inter.className} ${poppins.className}`}>
      <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
